name: shop
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  path: ^1.8.2
  location: ^4.2.0
  google_maps_flutter: ^2.2.1
  intl: ^0.17.0
  http: ^0.13.5
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/icon.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/product-placeholder.png
 
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
