name: shop
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  path: ^1.8.2
  location: ^4.2.0
  google_maps_flutter: ^2.2.1
  intl: ^0.18.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_modular: ^5.0.3
  localization: ^2.1.0
  flutter_launcher_icons: "^0.13.1"
  gif: ^2.2.0
  flutter_carousel_slider: ^1.1.0
  mask_text_input_formatter: ^2.4.0

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/images/SNAP_LOGO.PNG.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "lib/assets/images/SNAP_LOGO.PNG.png"
  
flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/
    - lib/assets/fonts/
 
  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf
        - asset: lib/assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf
